what
Signed-off-by: Andrew Harding <azdagron@gmail.com>

diff --git a/test/integration/suites/datastore-mysql/01-test-variants b/test/integration/suites/datastore-mysql/01-test-variants
--- a/test/integration/suites/datastore-mysql/01-test-variants
+++ b/test/integration/suites/datastore-mysql/01-test-variants
@@ -47,11 +47,11 @@ test-mysql() {
     fi
 
     log-info "running tests against ${SERVICE}..."
-    ./mysql.test || fail-now "tests failed"
+    if ! ./mysql.test ; then
+        docker-compose logs "${SERVICE}"
+        fail-now "tests failed"
+    fi
     docker-stop "${SERVICE}"
 }
 
-test-mysql mysql-5-5 || exit 1
-test-mysql mysql-5-6 || exit 1
-test-mysql mysql-5-7 || exit 1
 test-mysql mysql-8-0 || exit 1
